### ISSUE TITLE
Install registry plugin to all versions of helm

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken-tools#134]
Currently, there is a discrepancy between helm server and client versions when running up a <1.7 k8s cluster with kraken [(issue here)](https://github.com/samsung-cnct/kraken/issues/172) .

Currently, we only install the registry plugin to the system default, and we should do so  for all helm versions.

**Comment by coffeepac** [comment]
@joejulian please take a look and see if this is a short term fix for us.

**Comment by joejulian** [comment]
The short-term fix is to set the PATH environment such that the version of helm we wish to use is earlier in the path.

When helm calls appr, appr downloads a chart and then calls `helm` (no path) to deploy it. This ends up grabbing helm from the default path (`/usr/bin/helm` which is symlinked to `/opt/cnct/kubernetes/v1.7/bin/helm`). By changing the path to point to the correct bin directory first, all not-fully-qualified bin references will still use the right binary.

**Comment by coffeepac** [comment]
I'm putting this into kraken.  closing as the upstream issue is also tracked in kraken.

**Comment by joejulian** [comment]
This workaround should probably be done in `ansible/roles/kraken.services/tasks/run-services.yaml`

**Comment by coffeepac** [comment]
fair, needs to be in both locations.  however, I don't think there is any work to be done in kraken-tools.

**Comment by joejulian** [comment]
lol, oops
