### ISSUE TITLE
Fix Image Vulnerability

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-tools#141]
Fix this vulnerability: https://quay.io/repository/samsung_cnct/kraken-tools/image/c34a9b1308c00cf2fe62b79177676798e4ebb69fdfc2b072fc1eb752707ec398?tab=vulnerabilities in the `curl` package.

**Comment by davidewatson** [comment]
This was fixed during yesterdays v0.6 release of kraken-tools because apk installed versions are not pinned. So even if we fixed #100, our Dockerfiles would still not be completely repeatable.
