### ISSUE TITLE
Cut a new crash-app release and include this in the kraken-tools Dockerfile

### ISSUE THREAD

**Issue by oneilcin** [samsung-cnct/kraken-tools#144]
A new release of crash-app would send a datetime with the log data, and send this to a new CNAME 'krakencrashreporter' for kibana viewing.

**Comment by philoserf** [comment]
while we are there we could turn this

```Dockerfile
RUN     wget -q https://github.com/samsung-cnct/k2-crash-application/releases/download/0.1.0/k2-crash-application_0.1.0_linux_amd64.tar.gz && \
        tar -zxvf k2-crash-application_0.1.0_linux_amd64.tar.gz  && \
        mv k2-crash-application /usr/bin/k2-crash-application && \
        rm -f k2-crash-application_0.1.0_linux_amd64.tar.gz
```

into this

```Dockerfile
RUN     wget -q -O crashapp.tgz https://github.com/samsung-cnct/k2-crash-application/releases/download/0.1.0/k2-crash-application_0.1.0_linux_amd64.tar.gz && \
        tar -zxvf crashapp.tgz  && \
        mv k2-crash-application /usr/bin/k2-crash-application && \
        rm -f crashapp.tgz
```

So that when release changes on a single line requires an edit.

**Comment by oneilcin** [comment]
A new tarball release that contains the latest built binary of k2-crash-application needs to be built.
The new binary will then be added to the Dockerfile.

If I manually build the k2-crash-application and run it, it does send the datetime to Elasticsearch.  Here is the URL to kibana in production: http://a1ce4d7c97e1f11e79f0d0e5525d7602-800400731.us-east-1.elb.amazonaws.com:5601/
Just choose the 'krakencrashreporter' drop down index.  I just sent a log on October 23.

**Comment by joejulian** [comment]
Would be even more condensed to do:
```
RUN     wget -q -O - https://github.com/samsung-cnct/k2-crash-application/releases/download/0.1.0/k2-crash-application_0.1.0_linux_amd64.tar.gz | \
        tar -zxC /usr/bin
```
