### ISSUE TITLE
fix image vulnerability

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-tools#149]
fix this vulnerability in kraken-tools image: https://quay.io/repository/samsung_cnct/kraken-tools/image/cc736fb576a7bc62f6e8d295de24b657064fa38951a2d607136b3e5c52b5f458?tab=vulnerabilities&fixable=true

**Comment by oneilcin** [comment]
This is passing 100%, version 0.7, and latest as of Nov 3 look good.

https://quay.io/repository/samsung_cnct/kraken-tools?tab=tags
