### ISSUE TITLE
Add ansible lint testing

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-tools#25]
https://github.com/samsung-cnct/k2/issues/251 handles lint testing ansible as a pre-commit. Add lint testing to the CI tests.

**Comment by coffeepac** [comment]
blocked by CI

**Comment by coffeepac** [comment]
details of work completed for this are in samsunc-cnct/k2#254

**Comment by coffeepac** [comment]
this has been added to kraken-lib.  there is nothing in kraken-tools that should be getting linted (ie no original code, only deps)
