### ISSUE TITLE
Change ENVs to ARGs when it's only used in Dockerfile

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-tools#93]
We should only use ENVs if they're used in an application, like K2. For Dockerfile needs, we should use ARGs instead. This will help avoid the question of whether or not the ENV entry is being used elsewhere when we reorganize the Dockerfile.

**Comment by davidewatson** [comment]
We should probably do this for some existing `ENV` instructions, but TIL from the [documentation](https://docs.docker.com/engine/reference/builder/#arg):

> The ARG instruction defines a variable that users can pass at build-time to the builder with the docker build command using the --build-arg <varname>=<value> flag. If a user specifies a build argument that was not defined in the Dockerfile, the build outputs a warning.

Version numbers and the like are obvious candidates. Some other bits like package lists might not be so amenable.
